# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "nvme" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/9052a3bc-c2c0-42a8-b87d-abba5320d334";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/8860-2802";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  fileSystems."/windows" =
  {
    device = "/dev/nvme0n1p3";
    fsType = "ntfs-3g"; 
    options = [ "rw" "uid=1000"];
  };

  swapDevices = [ {
    device = "/var/lib/swapfile";
    # discard=once is mentioned to be better?
    options = [ "discard" ]; # equivalent to swapon --discard
    size = 16*1024;
  }];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp0s20f3.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

  hardware.logitech.wireless.enable = true;

  hardware.printers = {
    ensurePrinters = [
      {
        name = "Kyocera-TASKalfa-5053ci-KPDL";
        location = "Home";
        deviceUri = "ipp://xxx/ipp/Print2Follow";
        model = "drv:///sample.drv/generic.ppd";
        #model = "../../modules/ppds/en_Kyocera_TASKalfa_5053ci(Mitarbeiter).ppd";
        ppdOptions = {
        PageSize = "A4";
        User = "xxx";
        };
      }
    ];
    ensureDefaultPrinter = "Kyocera-TASKalfa-5053ci-KPDL";
  };
}
